# Generated by Django 6.0.7 on 2026-07-31 21:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FicheMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('num_marche', models.CharField(max_length=50, unique=True, verbose_name='Numéro de marché')),
                ('type_budget', models.CharField(choices=[('INV', 'Investissement'), ('EXP', 'Exploitation')], max_length=5, verbose_name='Type de budget')),
                ('imputation_budgetaire', models.CharField(help_text='Exemple : 980.912.50.53', max_length=50, verbose_name='Imputation budgétaire')),
                ('objet', models.TextField(verbose_name='Objet du marché')),
                ('titulaire', models.CharField(max_length=255, verbose_name='Titulaire du marché')),
                ('mode_passation', models.CharField(choices=[('AOO', "Appel d'offres ouvert"), ('AOS', "Appel d'offres ouvert simplifié"), ('AOP', "Appel d'offres avec présélection"), ('AON', "Appel d'offres national"), ('AOI', "Appel d'offres international"), ('AOR', "Appel d'offres restreint"), ('CONCOURS', 'Concours'), ('NEGOCIEE', 'Procédure négociée')], max_length=10, verbose_name='Mode de passation')),
                ('type_marche', models.CharField(choices=[('MARCHE_CADRE', 'Marché cadre'), ('MARCHE_RECONDUCTIBLE', 'Marché reconductible'), ('MARCHE_ALLOTIS', 'Marché alloti'), ('MARCHE_CONCEP_REALISATION', 'Marché conception-réalisation'), ('MARCHE_TRANCHES_CONDITIONNELLES', 'Marché à tranches conditionnelles'), ('DIALOGUE_COMPETITIF', 'Dialogue compétitif'), ('OFFRE_SPONTANEE', 'Offre spontanée')], max_length=35, verbose_name='Type de marché')),
                ('exercice_budgetaire', models.PositiveSmallIntegerField(db_index=True, verbose_name='Exercice budgétaire')),
                ('rib', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator(message='Un RIB marocain comporte exactement 24 chiffres.', regex='^\\d{24}$')], verbose_name='RIB')),
                ('dom_bancaire', models.CharField(max_length=255, verbose_name='Domiciliation bancaire')),
                ('date_notif_appro', models.DateField(blank=True, null=True, verbose_name="Date de notification d'approbation")),
                ('delai_execution', models.PositiveIntegerField(verbose_name="Délai d'exécution (mois)")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant hors taxe')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de TVA')),
                ('taux_rabais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='En pourcentage, exemple: 12.45', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rabais')),
                ('taux_majoration', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='En pourcentage, exemple: 14.05', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Majoration')),
                ('avenant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='Montant des avenants')),
                ('montant_global_ttc', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True, verbose_name='Montant global TTC')),
                ('caution_provisoire', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Caution provisoire')),
                ('caution_definitive', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Caution définitive')),
                ('retenue_garantie', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Retenue de garantie')),
                ('marche_solde', models.BooleanField(default=False, verbose_name='Marché soldé')),
                ('marche_resilie', models.BooleanField(default=False, verbose_name='Marché résilié')),
                ('info_supp', models.TextField(blank=True, verbose_name='Informations supplémentaires')),
            ],
            options={
                'verbose_name': 'Fiche marché',
                'verbose_name_plural': 'Fiches marché',
                'ordering': [models.OrderBy(models.F('date_notif_appro'), descending=True, nulls_last=True), 'num_marche'],
                'indexes': [models.Index(fields=['type_budget', 'exercice_budgetaire'], name='marche_fich_type_bu_a85d28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Nantissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('num_acte', models.CharField(max_length=50, verbose_name="Numéro de l'acte de nantissement")),
                ('date_nant', models.DateField(verbose_name='Date de nantissement')),
                ('mtt_nant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant nanti')),
                ('entite_nant', models.CharField(help_text='Interprété comme la banque en faveur de laquelle le nantissement est constitué (cohérent avec RIB/domiciliation ci-dessous) plutôt que le titulaire du marché -- à confirmer.', max_length=255, verbose_name='Entité bénéficiaire du nantissement')),
                ('rib', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator(message='Un RIB marocain comporte exactement 24 chiffres.', regex='^\\d{24}$')], verbose_name='RIB')),
                ('dom_banc', models.CharField(max_length=255, verbose_name='Domiciliation bancaire')),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='marche.fichemarche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Nantissement',
                'verbose_name_plural': 'Nantissements',
                'ordering': ['-date_nant'],
            },
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('num_penalite', models.CharField(max_length=50, verbose_name='Numéro de la pénalité')),
                ('date_penalite', models.DateField(verbose_name='Date de la pénalité')),
                ('mtt_penalite', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la pénalité')),
                ('motif_penalite', models.TextField(verbose_name='Motif de la pénalité')),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='marche.fichemarche', verbose_name='Marché')),
            ],
            options={
                'verbose_name': 'Pénalité',
                'verbose_name_plural': 'Pénalités',
                'ordering': ['-date_penalite'],
            },
        ),
    ]
