# Generated by Django 6.0.7 on 2026-07-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tresorerie',
            options={'ordering': ['-exercice', '-op'], 'verbose_name': 'Trésorerie', 'verbose_name_plural': 'Trésorerie'},
        ),
    ]
