# Generated by Django 6.0.7 on 2026-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tresorerie", "0004_tresorerie_marche_tresorerie_reference_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tresorerie",
            name="reference_document",
            field=models.CharField(
                blank=True,
                help_text="N° Bons de commande, n°Conventions, etc. (hors Marchés, heures supp, indemnités).",
                max_length=100,
                null=True,
                verbose_name="Référence",
            ),
        ),
    ]
