# Generated by Django 6.1.1 on 2026-10-03 21:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0005_alter_tresorerie_reference_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('exercice', models.PositiveSmallIntegerField(help_text='Année budgétaire (ex: 2026, 2025...)', unique=True, verbose_name='Exercice budgétaire')),
                ('credit_exploitation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Crédit budgétaire alloué en dirhams (Exploitation)', max_digits=15, verbose_name='Crédit Exploitation')),
                ('credit_investissement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Crédit budgétaire alloué en dirhams (Investissement)', max_digits=15, verbose_name='Crédit Investissement')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation / Notes')),
            ],
            options={
                'verbose_name': 'Budget par Exercice',
                'verbose_name_plural': 'Budgets par Exercice',
                'ordering': ['-exercice'],
            },
        ),
    ]
