# Generated by Django 6.1.1 on 2026-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0006_budgetexercice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('exercice', models.PositiveSmallIntegerField(help_text="Année de l'exercice (ex: 2026)", verbose_name='Exercice budgétaire')),
                ('num_ordre', models.PositiveIntegerField(verbose_name="N° d'ordre de recette")),
                ('date_decision', models.DateField(blank=True, null=True, verbose_name='Date de décision')),
                ('num_decision', models.CharField(blank=True, max_length=100, verbose_name='N° de décision')),
                ('debiteur', models.CharField(max_length=255, verbose_name='Débiteur')),
                ('nature', models.CharField(choices=[('ALIMENTATION DE LA TRESORERIE', 'Alimentation de la trésorerie'), ('RECETTES CONFISCATION', 'Recettes confiscation'), ('PENALITES DE RETARD', 'Pénalités de retard'), ('REJET DE LA TGR', 'Rejet de la TGR')], max_length=50, verbose_name='Nature')),
                ('budget', models.CharField(choices=[('EXPLOITATION', 'Exploitation'), ('INVESTISSEMENT', 'Investissement')], max_length=20, verbose_name='Budget')),
                ('date_encaissement', models.DateField(blank=True, null=True, verbose_name="Date d'encaissement")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (DH)')),
                ('etat', models.CharField(choices=[('NON ETABLI', 'Non établi'), ('ETABLI', 'Établi')], default='NON ETABLI', max_length=20, verbose_name='État')),
                ('observation', models.TextField(blank=True, verbose_name='Observation / Notes')),
            ],
            options={
                'verbose_name': 'Ordre de Recette',
                'verbose_name_plural': 'Ordres de Recette',
                'ordering': ['-exercice', 'num_ordre'],
                'indexes': [models.Index(fields=['exercice', 'num_ordre'], name='tresorerie__exercic_9a2600_idx')],
            },
        ),
    ]
